name: Build Kivy APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # বিল্ডোজার ক্যাশ সেটআপ (সময় বাঁচানোর আসল যাদু এখানে)
      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Execute Build Script
        run: |
          chmod +x comandList.sh
          ./comandList.sh
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kivy-App-APK
          path: bin/*.apk
